CREATE TABLE IF NOT EXISTS Similares
(
    ASIN_produto CHAR(10) NOT NULL,
    ASIN_similar CHAR(10) NOT NULL CHECK (ASIN_produto <> ASIN_similar),
    FOREIGN KEY (ASIN_produto) REFERENCES Produto(ASIN)/*,
    FOREIGN KEY (ASIN_similar) REFERENCES Produto(ASIN)  ----- TALVEZ TENHA PRODUTOS FORA DA LISTA QUE SAO SIMILARES*/
);